### ISSUE TITLE
use workload identity

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#17]
you can have a GSA for a workload. might be useful for limiting access

**Comment by sirdarckcat** [comment]
had to revert in https://github.com/google/kctf/pull/77

**Comment by sirdarckcat** [comment]
Error was:
   https://github.com/google/kctf/runs/660654663?check_suite_focus=true#step:8:30

Also, this means that creating a cluster needs Owner permissions (Editor is not enough) since binding IAM permissions requires an additional permission (set IAM policy role, requires IAM Admin)

**Comment by gree-gorey** [comment]
Is it an existing cluster?

I think that's because during the cluster creation one needs to use additional flag `--workload-pool` as I did in https://github.com/google/kctf/pull/75/commits/152e144d599d595e4ca0848abc47790eb649febe#diff-bb8a8efddd63e9c2d15b46c10737fbfaR29

I will try to adjust that so it can add this pool to existing cluster.

**Comment by gree-gorey** [comment]
Smth like
```
gcloud container clusters update ${CLUSTER_NAME} --workload-pool=${PROJECT}.svc.id.goog
```

should do. I just didn't account for existing clusters.

**Comment by sirdarckcat** [comment]
@gree-gorey - I added you to the ACL of the project, could you make the change and then merge your change again plz? :)

**Comment by sirdarckcat** [comment]
it's called `kctf-github-ci`

**Comment by gree-gorey** [comment]
I think we can close this one? It is implemented for GCS; are there any other services in GCP that we connect to from k8s?
