### ISSUE TITLE
Unify versions

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#230]
we have 3 things to version:
1. the operator
2. the challenge api
3. the sdk

the docker images are actually included in the SDK and/or the operator (depending on which image, external-dns is in operator, but nsjail is in sdk, for example)

https://github.com/google/kctf/blob/052e00174cbe63c6b836955a2c5babbb74b3a3bb/kctf-operator/version/version.go#L4
https://github.com/google/kctf/blob/052e00174cbe63c6b836955a2c5babbb74b3a3bb/kctf-operator/pkg/apis/kctf/v1alpha1/register.go#L15
and the SDK should also have a version (it doesnt have one atm)

if we use the same namespace for all, then we kindof end up with having to make releases for things we dont need releases, just for the sake of changing the number..

thoughts?

**Comment by sroettger** [comment]
> if we use the same namespace for all, then we kindof end up with having to make releases for things we dont need releases, just for the sake of changing the number..

I don't think I follow, can you give an example?

My thoughts were that we pretty much only support a setup where all versions fit together. I.e. if you change the sdk, you also need to upgrade the cluster (which upgrades the operator and the challenge api)

**Comment by sirdarckcat** [comment]
Mostly just that the challenge.yaml / API version will increase on every SDK change, which is a bit strange :-)

**Comment by sroettger** [comment]
why does it have to?

**Comment by sirdarckcat** [comment]
If they are unified? Because then they all move at the same time.

**Comment by sroettger** [comment]
The cluster should always run a version that fits the SDK.
I.e. if you upgrade the sdk, you should also upgrade the cluster. The operator doesn't really need a version (besides that the sdk wants it) so we can just always set it to the same version as the sdk.

There's no point in upgrading a challenge to a newer version than the sdk, so we don't have to support newer challenges on older clusters. If you import a challenge from somewhere else to your challenge directory, it's your responsibility to make sure that it's compatible.

We do want to support minor version changes though, that is upgrade the sdk to a new minor version without upgrading all challenges. To support changing the CRD in a minor version, we will need to have an independent version in the crd (as we have now). Whenever we make a change, we increment the version. The operator needs to support all versions from the major sdk version.

When we release a new sdk version, we drop support for all CRD versions except the latest.

The sdk version should probably be in a text file under the kctf folder. So that if you want to upgrade the sdk, you know which version you're upgrading from.

Anything else?

**Comment by sirdarckcat** [comment]
Sounds good to me
